name: java

on:
  pull_request:
    paths:
      - '**.java'
      - java/app/build.gradle.kts
      - .github/workflows/java.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: setup gradle
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: java

      - name: test
        working-directory: java
        run: |
          ./gradlew test

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
        with:
          build-root-directory: java

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          build-root-directory: java
